#ifndef ENGINE_INPUTDATA_H
#define ENGINE_INPUTDATA_H

#include <string>
#include <unordered_map>
#include <raylib.h>

#define KEYDATA(input_key) { #input_key, KEY_##input_key }
static std::unordered_map<std::string, KeyboardKey> stringToKeyboardKey = {
    KEYDATA(NULL),
    KEYDATA(A),
    KEYDATA(B),
    KEYDATA(C),
    KEYDATA(D),
    KEYDATA(E),
    KEYDATA(F),
    KEYDATA(G),
    KEYDATA(H),
    KEYDATA(I),
    KEYDATA(J),
    KEYDATA(K),
    KEYDATA(L),
    KEYDATA(M),
    KEYDATA(N),
    KEYDATA(O),
    KEYDATA(P),
    KEYDATA(Q),
    KEYDATA(R),
    KEYDATA(S),
    KEYDATA(T),
    KEYDATA(U),
    KEYDATA(V),
    KEYDATA(W),
    KEYDATA(X),
    KEYDATA(Y),
    KEYDATA(Z),

    KEYDATA(ZERO),
    KEYDATA(ONE),
    KEYDATA(TWO),
    KEYDATA(THREE),
    KEYDATA(FOUR),
    KEYDATA(FIVE),
    KEYDATA(SIX),
    KEYDATA(SEVEN),
    KEYDATA(EIGHT),
    KEYDATA(NINE),

    KEYDATA(PAUSE),
    KEYDATA(ESCAPE),

    KEYDATA(LEFT_CONTROL),
    KEYDATA(LEFT_SHIFT),
    KEYDATA(LEFT_ALT),
    KEYDATA(LEFT_SUPER),

    KEYDATA(RIGHT_CONTROL),
    KEYDATA(RIGHT_SHIFT),
    KEYDATA(RIGHT_ALT),
    KEYDATA(RIGHT_SUPER),

    KEYDATA(KB_MENU),

    KEYDATA(LEFT_BRACKET),
    KEYDATA(RIGHT_BRACKET),
    KEYDATA(SEMICOLON),
    KEYDATA(COMMA),
    KEYDATA(PERIOD),
    KEYDATA(APOSTROPHE),
    KEYDATA(SLASH),
    KEYDATA(BACKSLASH),

    KEYDATA(MINUS),

    KEYDATA(SPACE),
    KEYDATA(BACKSPACE),
    KEYDATA(TAB),
    KEYDATA(PAGE_UP),
    KEYDATA(PAGE_DOWN),

    KEYDATA(END),
    KEYDATA(HOME),
    KEYDATA(INSERT),
    KEYDATA(DELETE),

    KEYDATA(KP_DECIMAL),
    KEYDATA(KP_DIVIDE),
    KEYDATA(KP_MULTIPLY),
    KEYDATA(KP_SUBTRACT),
    KEYDATA(KP_ADD),
    KEYDATA(KP_ENTER),
    KEYDATA(KP_EQUAL),

    KEYDATA(LEFT),
    KEYDATA(RIGHT),
    KEYDATA(UP),
    KEYDATA(DOWN),

    KEYDATA(KP_0),
    KEYDATA(KP_1),
    KEYDATA(KP_2),
    KEYDATA(KP_3),
    KEYDATA(KP_4),
    KEYDATA(KP_5),
    KEYDATA(KP_6),
    KEYDATA(KP_7),
    KEYDATA(KP_8),
    KEYDATA(KP_9),

    KEYDATA(F1),
    KEYDATA(F2),
    KEYDATA(F3),
    KEYDATA(F4),
    KEYDATA(F5),
    KEYDATA(F6),
    KEYDATA(F7),
    KEYDATA(F8),
    KEYDATA(F9),
    KEYDATA(F10),
    KEYDATA(F11),
    KEYDATA(F12),
};
#undef KEYDATA

#endif
